from django.conf.urls import patterns, url
from cpanel import views

urlpatterns = patterns('',
	url(r'^$', views.dashboard, name="dashboard"),
	url(r'^products/', views.products, name="products"),
	url(r'^newproduct/', views.new_product, name="new_product"),
    url(r'^product/(?P<product_slug>[\w\-]+)/$', views.product, name="product"),
    url(r'^editproduct/(?P<product_slug>[\w\-]+)/$', views.edit_product, name="edit_product"),
    url(r'^productimages/new/(?P<product_slug>[\w\-]+)/$', views.new_image, name="new_image"),
    url(r'^productimages/new/', views.new_image, name="new_image"),
    url(r'^productimages/delete/(?P<image_id>\d+)/$', views.delete_image, name="delete_image"),
    url(r'^categories/', views.categories, name="categories"),
    url(r'^newcat/', views.new_category, name="new_cat"),
    url(r'^stock/', views.stock, name="stock"),
    url(r'^item/(?P<item_id>\d+)', views.item, name="item"),
    url(r'^purchase/(?P<purchase_id>\d+)', views.purchase, name="purchase"),
    url(r'^purchases/new', views.new_purchase, name="new_purchase"),
    url(r'^purchases/', views.purchases, name="purchases"),
    url(r'^suppliers/new/', views.new_supplier, name="supplier_new"),
    url(r'^suppliers/', views.suppliers, name="suppliers"),
    url(r'^supplier/(?P<supplier_id>\d+)', views.supplier, name="supplier"),
    url(r'^supplier/edit/(?P<supplier_id>\d+)/$', views.edit_supplier, name="edit_supplier"),
    url(r'^contacts/new/', views.new_contact, name="new_contact"),
    url(r'^contact/edit/(?P<contact_id>\d+)/$', views.edit_contact, name="edit_contact"),
    url(r'^contacts/', views.contacts, name="contacts"),
    url(r'^blog/', views.blog, name="blog"),
    url(r'^toggle_for_sale/', views.toggle_for_sale, name="toggle_for_sale"),
    url(r'^sales/$', views.sales, name="sales"),
    #url(r'^sales/(?P<search>[\w\-]+)/$', views.sales, name="sales"),
    url(r'^shipping/(?P<order_ref>[\w\-]+)/$', views.shipping, name="shipping"),
    url(r'^invoice/(?P<order_ref>[\w\-]+)/$', views.invoice, name="invoice"),
    url(r'^inbox/$', views.inbox, name="inbox"),
    url(r'^report/$', views.report, name="report"),
	)